services:
  app:
    build:
      context: .
      dockerfile: Dockerfile
    container_name: mafit_app
    restart: unless-stopped
    working_dir: /var/www
    volumes:
      - ./:/var/www
      - ./docker/php/local.ini:/usr/local/etc/php/conf.d/local.ini
    networks:
      - mafit-network

  nginx:
    image: nginx:alpine
    container_name: mafit_nginx
    restart: unless-stopped
    ports:
      - "8080:80"
    volumes:
      - ./:/var/www
      - ./docker/nginx/default.conf:/etc/nginx/conf.d/default.conf
    networks:
      - mafit-network
    depends_on:
      - app

  mysql:
    image: mysql:8.0
    container_name: mafit_mysql
    restart: unless-stopped
    ports:
      - "3306:3306"
    environment:
      MYSQL_DATABASE: mafit
      MYSQL_ROOT_PASSWORD: root
      MYSQL_PASSWORD: root
      MYSQL_USER: mafit
    volumes:
      - mysql_data:/var/lib/mysql
    networks:
      - mafit-network

networks:
  mafit-network:
    driver: bridge

volumes:
  mysql_data:
    driver: local


